name: Run Telegram Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      run: python bot.py